/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The business the current token belongs to */
        get: operations["TenantsController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and database status */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard summary: last 7 days, items needing attention, upcoming visits */
        get: operations["OverviewController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the business's leads, newest first */
        get: operations["LeadsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations; ones needing the owner come first */
        get: operations["ConversationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One conversation with all its messages */
        get: operations["ConversationsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List appointments, soonest first */
        get: operations["AppointmentsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appointments/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a booking awaiting approval; texts the customer if they agreed */
        post: operations["AppointmentsController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appointments/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline a booking awaiting approval; frees the slot */
        post: operations["AppointmentsController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Free appointment slots on one day */
        get: operations["AvailabilityController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The agent's configuration (defaults if never saved) */
        get: operations["AgentSettingsController_get"];
        /** Replace the agent's configuration */
        put: operations["AgentSettingsController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test the agent with a sample conversation (no data is saved, no bookings) */
        post: operations["AgentController_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/widget/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public widget settings for a business (name, greeting, starter questions) */
        get: operations["ChatController_widget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a customer message; the reply streams back as NDJSON events
         * @description One JSON object per line: {"type":"conversation"} first, then {"type":"text"} chunks, optionally {"type":"suggestions"}, or {"type":"error"}.
         */
        post: operations["ChatController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TenantsController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverviewController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        period: {
                            /** Format: date-time */
                            from: string;
                            /** Format: date-time */
                            to: string;
                        };
                        stats: {
                            conversations: number;
                            resolvedByAi: number;
                            /** @description 0–1: share of conversations finished without a human */
                            aiResolutionRate: number;
                            newLeads: number;
                            appointmentsBooked: number;
                        };
                        needsAttention: {
                            /** Format: uuid */
                            conversationId: string;
                            customerName: string | null;
                            lastCustomerMessage: string | null;
                            summary: string | null;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                        upcomingAppointments: {
                            /** Format: uuid */
                            id: string;
                            customerName: string;
                            service: string;
                            /** Format: date-time */
                            startsAt: string;
                            /** @enum {string} */
                            status: "awaiting_approval" | "confirmed";
                        }[];
                        timeZone: string;
                    };
                };
            };
        };
    };
    LeadsController_list: {
        parameters: {
            query?: {
                stage?: "new" | "qualified" | "booked" | "won" | "lost";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            phone: string | null;
                            smsConsent: boolean;
                            service: string;
                            /** @enum {string} */
                            score: "hot" | "warm" | "cold";
                            /** @enum {string} */
                            stage: "new" | "qualified" | "booked" | "won" | "lost";
                            /** @description Whole dollars */
                            estimatedValue: number | null;
                            /** @enum {string} */
                            source: "website_chat" | "email" | "sms";
                            conversationId: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
    };
    ConversationsController_list: {
        parameters: {
            query?: {
                /** @description 1–100, default 50 */
                limit?: number;
                status?: "open" | "needs_owner" | "resolved_by_ai" | "resolved_by_owner";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            customerName: string | null;
                            /** @enum {string} */
                            channel: "website_chat" | "email" | "sms";
                            /** @enum {string} */
                            status: "open" | "needs_owner" | "resolved_by_ai" | "resolved_by_owner";
                            summary: string | null;
                            lastMessage: string | null;
                            messageCount: number;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    ConversationsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        customerName: string | null;
                        /** @enum {string} */
                        channel: "website_chat" | "email" | "sms";
                        /** @enum {string} */
                        status: "open" | "needs_owner" | "resolved_by_ai" | "resolved_by_owner";
                        summary: string | null;
                        lastMessage: string | null;
                        messageCount: number;
                        /** Format: date-time */
                        updatedAt: string;
                        messages: {
                            /** Format: uuid */
                            id: string;
                            /** @enum {string} */
                            role: "user" | "assistant";
                            content: string;
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                    };
                };
            };
            /** @description No such conversation for this business */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppointmentsController_list: {
        parameters: {
            query?: {
                /** @description ISO date-time, e.g. 2026-10-06T00:00:00Z */
                from?: unknown;
                status?: "awaiting_approval" | "confirmed" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The business's time zone, for displaying startsAt */
                        timeZone: string;
                        items: {
                            /** Format: uuid */
                            id: string;
                            customerName: string;
                            service: string;
                            address: string | null;
                            /** Format: date-time */
                            startsAt: string;
                            /** @enum {string} */
                            status: "awaiting_approval" | "confirmed" | "cancelled";
                            /** @enum {string} */
                            bookedBy: "ai_agent" | "staff";
                            leadId: string | null;
                        }[];
                    };
                };
            };
        };
    };
    AppointmentsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** @enum {string} */
                        status: "confirmed" | "cancelled";
                    };
                };
            };
            /** @description No such appointment for this business */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The booking is not awaiting approval anymore */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppointmentsController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** @enum {string} */
                        status: "confirmed" | "cancelled";
                    };
                };
            };
            /** @description No such appointment for this business */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The booking is not awaiting approval anymore */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityController_get: {
        parameters: {
            query: {
                date: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date */
                        date: string;
                        timeZone: string;
                        available: boolean;
                        /** @description Why nothing is available, when available is false */
                        reason?: string;
                        slots: {
                            /** Format: date-time */
                            startsAt: string;
                            /** @description Local time for display, e.g. 9:00 AM */
                            label: string;
                            /** @description Local time, 24-hour HH:MM */
                            value: string;
                        }[];
                    };
                };
            };
        };
    };
    AgentSettingsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agentName: string;
                        greeting: string;
                        /** @enum {string} */
                        tone: "friendly" | "professional" | "casual";
                        instructions: string;
                        tools: {
                            answerQuestions: boolean;
                            qualifyLeads: boolean;
                            bookAppointments: boolean;
                            followUps: boolean;
                        };
                        /** @enum {string} */
                        approvalMode: "review" | "auto";
                        suggestedQuestions: string[];
                    };
                };
            };
        };
    };
    AgentSettingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    agentName: string;
                    greeting: string;
                    /** @enum {string} */
                    tone: "friendly" | "professional" | "casual";
                    instructions: string;
                    tools: {
                        answerQuestions: boolean;
                        qualifyLeads: boolean;
                        bookAppointments: boolean;
                        followUps: boolean;
                    };
                    /** @enum {string} */
                    approvalMode: "review" | "auto";
                    suggestedQuestions: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agentName: string;
                        greeting: string;
                        /** @enum {string} */
                        tone: "friendly" | "professional" | "casual";
                        instructions: string;
                        tools: {
                            answerQuestions: boolean;
                            qualifyLeads: boolean;
                            bookAppointments: boolean;
                            followUps: boolean;
                        };
                        /** @enum {string} */
                        approvalMode: "review" | "auto";
                        suggestedQuestions: string[];
                    };
                };
            };
            /** @description Validation failed; see error.details for each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    messages: {
                        /** @enum {string} */
                        role: "user" | "assistant";
                        content: string;
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reply: string;
                        suggestions: string[] | null;
                        toolCalls: {
                            name: string;
                            isError: boolean;
                        }[];
                        usage: {
                            model: string;
                            inputTokens: number;
                            outputTokens: number;
                        };
                    };
                };
            };
        };
    };
    ChatController_widget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tenantSlug: string;
                        businessName: string;
                        agentName: string;
                        greeting: string;
                        suggestedQuestions: string[];
                    };
                };
            };
        };
    };
    ChatController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenantSlug: string;
                    /** Format: uuid */
                    conversationId?: string;
                    message: string;
                };
            };
        };
        responses: {
            /** @description Too many messages; slow down */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
